name = "Test Level"

[textures]
wall = { path = "assets/rpg.png", t = 448, l = 96, w = 32, h = 32, rigid = true }
watter = { path = "assets/rpg.png", t = 704, l = 1188, w = 32, h = 32 }

# 
[render_targets]
wall = [
	[0, 0],
	[0, 32],
	[32, 0],
	[0, 64],
	[64, 0]
]
watter = [ 
	[32, 32],
	[32, 64],
	[64, 32],
	[64, 64]
]
