name = "Test Level"

[textures]
wall = { path = "assets/floor.png", t = 0, b = 32, l = 32, r = 32 }
floor = { path = "assets/floor.png", t = 32, b = 32, l = 0, r = 32 }

[render_targets]
wall = [
	[0, 0],
	[0, 32],
	[32, 0],
	[0, 64],
	[64, 0]
]
floor = [ 
	[32, 32],
	[32, 64],
	[64, 32],
	[64, 64]
]
