name = "Test Level"

[textures]
wall = { path = "assets/rpg.png", t = 448, l = 96, w = 32, h = 32, rigid = true }
watter = { path = "assets/rpg.png", t = 704, l = 1188, w = 32, h = 32 }

# 
[render_targets]
wall = [
	[0, 0],
	[0, 1],
	[1, 0],
	[0, 2],
	[2, 0]
]
watter = [ 
	[1, 1],
	[1, 2],
	[2, 1],
	[2, 2]
]
